-- ----------------------------------------------------------------------
-- Write your question with "--" prefix (SQL comment), highlight it (as with SQL clause)
-- and press Ctrl/Cmd + Enter to run query generated by AI.
-- (you can also force AI with Ctrl/Cmd + Shitf + Enter).
--
-- NOTE: If you have selected ollama AI, you need to have Ollama server running,
--       and the model loaded:
-- % ollama serve
-- % ollama pull duckdb-nsql:7b
-- ----------------------------------------------------------------------
--
-- Have monitoring database selected.
-- Highlight the question/line and press Ctrl/Cmd + Shift + Enter.
--
-- Show cost per month

-- Show total cost for current year

